# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:20-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY src ./src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Use a smaller Node.js image for the final image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy built files and package.json
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package-lock.json ./

# Install production dependencies
RUN npm install --ignore-scripts --omit=dev

# Set environment variables
ENV SHOPIFY_ACCESS_TOKEN=<YOUR_ACCESS_TOKEN>
ENV MYSHOPIFY_DOMAIN=<YOUR_SHOP>.myshopify.com

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]
