# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the TypeScript application
RUN npm run build

# Use a smaller Node.js image for the final image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/build ./build

# Copy necessary files
COPY package.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Set environment variables
ENV SHOPIFY_ACCESS_TOKEN=<YOUR_ACCESS_TOKEN>
ENV MYSHOPIFY_DOMAIN=<YOUR_SHOP>.myshopify.com

# Run the server
CMD ["node", "build/index.js"]
